CREATE TABLE public.books (
    id bigint generated by default as identity primary key,
    title text not null,
    author text not null,
    isbn text,
    description text,
    price numeric(10,2) not null,
    stock integer not null default 0,
    category_id bigint,
    cover_url text,
    cover_path text,
    pdf_path text,
    created_at timestamptz not null default now()
);